// Package sqlc holds code generated by sqlc from sql/queries/*.sql.
//
// This file is a placeholder so the directory exists in fresh clones.
// Run `make sqlc-generate` to populate it.
package sqlc
