// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestPaymentByOrder = `-- name: GetLatestPaymentByOrder :one
SELECT id, user_id, order_id, amount, currency, status, created_at, updated_at
FROM payments
WHERE order_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPaymentByOrder(ctx context.Context, orderID pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getLatestPaymentByOrder, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, user_id, order_id, amount, currency, status, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :exec
INSERT INTO payments (id, user_id, order_id, amount, currency, status, created_at, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type InsertPaymentParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	OrderID   pgtype.UUID
	Amount    int64
	Currency  string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) error {
	_, err := q.db.Exec(ctx, insertPayment,
		arg.ID,
		arg.UserID,
		arg.OrderID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :execrows
UPDATE payments
SET status     = $1,
    updated_at = $2
WHERE id = $3
`

type UpdatePaymentStatusParams struct {
	Status    string
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePaymentStatus, arg.Status, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
