// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountOrdersByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetLatestPaymentByOrder(ctx context.Context, orderID pgtype.UUID) (Payment, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Convention: use sqlc.arg(<name>) for every parameter, not positional $N.
	// Keep arg names matching column names so generated Go field names stay
	// predictable (e.g. sqlc.arg(user_id) → UserID).
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	InsertPayment(ctx context.Context, arg InsertPaymentParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (int64, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (int64, error)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
}

var _ Querier = (*Queries)(nil)
